basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from store.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('account/', include('account.urls', namespace='account')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('export/', export_excel, name='export_excel'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
from .views import export_excel, import_data

app_name = 'store'

urlpatterns = [
     path('', views.all_products, name='all_products'),
     path('item/<slug:slug>/', views.product_detail, name='product_detail'),
     path('search/<slug:category_slug>/', views.category_list, name='category_list'),
     path('diagrams/',views.diagrams, name='diagrams'),
     path('export/', export_excel, name='export_excel'),
     path('import/', import_data, name='import_data'),
]

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from slugify import slugify

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)

class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'categories'
    
    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])
    
    def __str__(self):
        return self.name 

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    brand = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    products = ProductManager()
    objects = models.Manager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)
    
    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])
    
    def __str__(self):
        return self.title

store/views.py
from django.shortcuts import get_object_or_404, render
from .models import Category, Product
import pandas as pd
from django.http import JsonResponse
from django.http import HttpResponse
from openpyxl import Workbook
from django.utils import timezone
from openpyxl import load_workbook
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Count
from slugify import slugify
import decimal
from decimal import Decimal
from django.db import IntegrityError

def import_data(request):
    if request.method == 'POST':
        # Отримуємо файл з запиту POST
        file = request.FILES.get('file')
        if not file:
            return render(request, 'import.html', {'error': 'Файл не було вибрано'})

        # Відкриваємо файл з допомогою openpyxl
        workbook = load_workbook(file)
        # Отримуємо потрібний аркуш
        worksheet = workbook.active

        import_success = True  # допоміжна змінна для відстеження успіху імпорту
        # Створити порожній список продуктів
        products_to_create = []

        try:
            # Отримуємо дані з кожного рядка у файлі
            for row in worksheet.iter_rows(min_row=2):
                id = row[7].value
                if not str(id).isdigit():
                    import_success = False
                    return render(request, 'import.html', {'error': f'Поле "id" має некоректне значення: "{id}"'})
                id = int(id)
                if Product.objects.filter(id=id).exists():
                    import_success = False
                    return render(request, 'import.html', {'error': f'Продукт з id {id} вже існує'})
                brand = row[0].value
                category_id = row[2].value
                created = row[3].value
                created_by_id = row[5].value
                description = row[6].value
                image = row[8].value
                in_stock = row[9].value
                is_active = row[10].value
                slug = row[12].value or slugify(row[13].value)
                if Product.objects.filter(slug=slug).exists():
                    import_success = False
                    return render(request, 'import.html', {'error': f'Продукт з slug {slug} вже існує'})
                title = row[13].value
                category_name = row[1].value
                updated = row[14].value
                price_str = row[11].value
                
                if not price_str:
                    import_success = False
                    return render(request, 'import.html', {'error': 'Поле "price" не може бути порожнім'})

                try:
                    price = Decimal(price_str)
                except (decimal.InvalidOperation, TypeError, ValueError):
                    import_success = False
                    return render(request, 'import.html', {'error': 'Ви ввели некоректну ціну'})
                
                price_str = str(row[11].value)
                
                if ',' in price_str:
                    if not price_str.replace(',', '').isnumeric():
                        import_success = False
                        return render(request, 'import.html', {'error': 'Ви ввели некоректну ціну'})
                    price_str = price_str.replace(',', '.')

                if not category_id or not category_name:
                    import_success = False
                    return render(request, 'import.html', {'error': 'Не вказано категорію для продукту'})

                if category_id:
                    try:
                        category = Category.objects.get(id=category_id)
                    except Category.DoesNotExist:
                        category = Category(id=category_id, name=category_name)
                        category.save()
                else:
                    try:
                        category = Category.objects.get(name=category_name)
                    except Category.DoesNotExist:
                        category = Category(name=category_name, slug=slugify(category_name))
                        category.save()

                if category.id != category_id or category_name != category.name:
                    import_success = False
                    return render(request, 'import.html', {'error': f'Категорія з id {category_id} вже існує з іншим ім\'ям'})
                
                if import_success == False:
                    raise Exception('Помилка імпортування')
                if import_success == True:
                    # Створюємо новий об'єкт Product з отриманими даними і зберігаємо його
                    product = Product(
                        brand=brand,
                        category=category,
                        created=created,
                        created_by_id=created_by_id,
                        description=description,
                        id=id,
                        image=image,
                        in_stock=in_stock,
                        is_active=is_active,
                        price=price,
                        slug=slug or slugify(title),  # якщо slug не задано, генеруємо його з title
                        title=title,
                        updated=updated
                    )
                    # Додати продукт до списку
                    products_to_create.append(product)
        
        except Exception as e:
            # обробка помилки
            print('Сталась помилка:', str(e))
            return render(request, 'import.html', {'error': 'Сталась помилка під час імпортування даних'})
        
        slugs = [product.slug for product in products_to_create]
        if len(set(slugs)) != len(slugs):
            import_success = False
            return render(request, 'import.html', {'error': 'Є продукти з однаковими slug'})
        
        
        # Зберегти всі продукти одночасно
        try:
            Product.objects.bulk_create(products_to_create)
        except IntegrityError as e:
            print('Помилка збереження продуктів: ', e)         

        return render(request, 'import.html', {'success': 'Дані успішно імпортовано!'})
    else:
        return render(request, 'import.html')

def export_excel(request):
    # Отримати дані з моделі Product
    products = Product.objects.all().values('brand', 'category', 'category_id', 'created', 'created_by', 'created_by_id', 'description', 'id', 'image', 'in_stock', 'is_active', 'order_items', 'price', 'slug', 'title', 'updated')

    # Створити новий файл Excel
    wb = Workbook()
    ws = wb.active

    # Додати заголовки стовпців
    ws.append(['brand', 'category', 'category_id', 'created', 'created_by', 'created_by_id', 'description', 'id', 'image', 'in_stock', 'is_active', 'price', 'slug', 'title', 'updated'])

    # Додати дані з моделі до файлу Excel
    for product in products:
        # Конвертувати дати та часи до місцевого часового поясу та встановити tzinfo=None
        local_created = timezone.localtime(product['created']).replace(tzinfo=None)
        local_updated = timezone.localtime(product['updated']).replace(tzinfo=None)
        ws.append([product['brand'],product['category'], product['category_id'],local_created,product['created_by'],product['created_by_id'],product['description'],product['id'],product['image'],product['in_stock'], product['is_active'],product['price'], product['slug'],product['title'], local_updated])


    # Повернути файл Excel як HTTP-відповідь
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename=export.xlsx'
    wb.save(response)
    return response


def all_products(request):
    products = Product.objects.all()
    return render(request, 'store/home.html', {'products': products})

def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/detail.html', {'product': product})

def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})

from django.db.models import Count
from django.shortcuts import render
from .models import Product, Category


def diagrams(request):
    categories = Category.objects.annotate(product_count=Count('product'))
    
    productsCatgId_list = []
    number_list = []
    
    for category in categories:
        productsCatgId_list.append(category.name)
        number_list.append(category.product_count)
    
    brand_dict = {}

    for product in Product.objects.all():
        brand = product.brand

        # increment brand count
        if brand in brand_dict:
            brand_dict[brand] += 1
        else:
            brand_dict[brand] = 1

    brand_list = list(brand_dict.keys())
    brand_number = list(brand_dict.values())

    context = {
        'productsCatgId_list': productsCatgId_list,
        'number_list': number_list,
        'brand_list': brand_list,
        'brand_number': brand_number
    }
    
    return render(request, 'store/diagrams.html', context)

templates/store/products/category.html
{% extends "../base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}


<main>
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">{{category.name|title}}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
          <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">

            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">250 ml</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

templates/store/products/detail.html
{% extends "../base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" background-size: cover width: 100% height:100% alt="Responsive image" src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p>Країна ТМ: <span class="lead">{{ product.brand }}</span></p>
                <p>{{ product.description}}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Price</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">${{ product.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                <select id="select">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>

                            </div>
                            <div class="col-6 text-end">
<button type="button" id="add-button" value="{{product.id}}" class="btn btn-secondary btn-sm">Add to basket</button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

</div>

<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
               document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>

{% endblock %}